# Generated by Django 4.0 on 2022-04-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('hireDate', models.DateField()),
                ('job', models.CharField(max_length=100)),
            ],
        ),
    ]
