# Generated by Django 4.0 on 2022-04-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interns',
            new_name='Employee',
        ),
    ]
