# Generated by Django 4.0 on 2022-04-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_interns_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='markAttendance',
            field=models.CharField(blank=True, choices=[('absent', 'Absent'), ('present', 'Present')], max_length=8),
        ),
        migrations.AddField(
            model_name='employee',
            name='task',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
